// Auto-generated composition from editor export
// Generated by parse_export.py

if (isNil "DYN_ground_objects") then { DYN_ground_objects = []; };

// Helper: create object with rotation (all use createVehicle for ATL positioning)
private _cv = {
    params ["_t","_p","_d","_u"];
    private _o = createVehicle [_t,_p,[],0,"CAN_COLLIDE"];
    _o setVectorDirAndUp [_d,_u];
    DYN_ground_objects pushBack _o;
    _o
};

private _o = objNull;

["Land_Mil_WallBig_4m_F",[7367.05,6392.27,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7368.8,6388.66,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7370.51,6385.04,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7372.23,6381.42,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7373.98,6377.81,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7375.74,6374.2,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7377.45,6370.58,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7379.2,6366.98,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7381.71,6366.25,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7385.34,6367.94,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7388.99,6369.59,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7392.64,6371.25,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7396.28,6372.93,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7399.92,6374.62,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7404.41,6373.29,0],[0.925095,0.379736,0],[0,0,1]] call _cv;

["Land_BarGate_F",[7355.12,6394.56,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_HBarrierTower_F",[7355.78,6386.06,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_HBarrierTower_F",[7348.22,6401.83,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7362.3,6386.28,0],[0.367001,-0.930221,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7366.64,6389.62,0],[0.924304,0.381656,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7348.85,6429.75,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7350.6,6426.15,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7352.31,6422.52,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7354.03,6418.9,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7355.78,6415.29,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7357.53,6411.69,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7359.24,6408.07,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7360.99,6404.46,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7358.49,6406,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7375.18,6443.59,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7371.52,6441.95,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7367.85,6440.35,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7364.18,6438.75,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7360.51,6437.11,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7356.86,6435.47,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7353.18,6433.87,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7349.53,6432.23,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7407.87,6380.2,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7406.15,6383.81,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7402.78,6391.08,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7401.05,6394.7,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7399.33,6398.32,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7397.64,6401.95,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7395.92,6405.57,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7396.78,6408.37,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7400.41,6410.06,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7407.71,6413.36,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7411.35,6415.05,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7414.98,6416.74,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7418.64,6418.39,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7422.09,6420.33,0],[-0.546163,0.837679,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7404.59,6455.94,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7400.9,6454.37,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7397.2,6452.85,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7393.5,6451.32,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7389.8,6449.75,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7386.11,6448.19,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7382.41,6446.66,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7378.72,6445.09,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7421.92,6423.95,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7420.29,6427.42,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7418.65,6430.9,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7417.01,6434.39,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7415.38,6437.88,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7413.73,6441.33,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7412.09,6444.81,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7410.46,6448.29,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7408.82,6451.77,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7407.18,6455.25,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7354.81,6413.69,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7351.1,6421.53,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7347.38,6429.1,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7374.28,6444.65,0],[0.377206,-0.926129,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7366.47,6441.22,0],[0.377206,-0.926129,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7358.51,6437.77,0],[0.377206,-0.926129,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7350.83,6434.29,0],[0.377206,-0.926129,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7382.2,6448.16,0],[-0.361168,0.932501,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7390.07,6451.46,0],[-0.361168,0.932501,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7398.08,6454.78,0],[-0.361168,0.932501,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7403.94,6457.31,0],[-0.361168,0.932501,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7420.7,6430.76,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7417.02,6438.45,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7413.31,6446.29,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7409.59,6453.86,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7422.53,6426.8,0],[0.901159,0.43349,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7383.86,6365.42,0],[-0.351307,0.93626,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7377.63,6366.48,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7373.92,6374.32,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7370.2,6381.89,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7391.67,6368.86,0],[-0.413415,0.910543,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7398.67,6370.59,0],[-0.008841,0.999961,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7408.33,6382.84,0],[-0.920247,-0.391338,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7399.16,6402.12,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7401.09,6398.3,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7400.08,6408.01,0],[-0.403347,0.915047,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7352.8,6406.35,0],[0.372911,-0.927867,0],[0,0,1]] call _cv;

_o = ["Land_Razorwire_F",[7343.16,6400.14,0],[0.90327,0.429073,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_Razorwire_F",[7351.74,6383.12,0],[0.90327,0.429073,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_Razorwire_F",[7356.71,6381.91,0],[0.427332,-0.904095,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_Razorwire_F",[7362.94,6384.72,0],[-0.40814,0.91292,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_Razorwire_F",[7345.34,6405.03,0],[-0.40814,0.91292,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_Razorwire_F",[7352.19,6408.26,0],[-0.40814,0.91292,0],[0,0,1]] call _cv;
_o allowDamage false;

["Land_CncBarrierMedium4_F",[7353.15,6389.26,0],[0.422665,-0.906286,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium4_F",[7348.79,6397.67,0],[0.422665,-0.906286,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7358.15,6402.11,0],[0.405091,-0.914277,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7356.46,6401.34,0],[0.405091,-0.914277,0],[0,0,1]] call _cv;

["Land_CampingTable_small_F",[7356.14,6405.39,0.08912],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_ConnectorTent_01_NATO_closed_F",[7355.51,6404.24,0.08912],[0.910646,0.413187,0],[0,0,1]] call _cv;

_o = ["Land_CzechHedgehog_01_new_F",[7344.73,6396.49,0],[0.90327,0.429073,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7349.37,6387.06,0],[0.558837,-0.829277,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7341.16,6403.51,0],[0.610151,0.792285,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7354.66,6409.65,0],[0.610151,0.792285,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7348.35,6406.72,0],[0.610151,0.792285,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7353.24,6379.92,0],[-0.279131,0.960253,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7359.26,6382.87,0],[0.610151,0.792285,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7365.94,6385.79,0],[0.610151,0.792285,0],[0,0,1]] call _cv;
_o allowDamage false;

["Land_CncBarrierMedium_F",[7352.99,6399.62,0],[0.421256,-0.906942,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7351.83,6400.21,0],[0.908492,0.417902,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7360.55,6392.59,0],[-0.405035,0.914301,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7362.22,6393.37,0],[-0.435883,0.900003,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7363.38,6392.8,0],[-0.901608,-0.432555,0],[0,0,1]] call _cv;

["Land_Cargo_Patrol_V3_F",[7352.59,6429.74,0],[0.420555,-0.907267,0],[0,0,1]] call _cv;

["Land_Cargo_Patrol_V3_F",[7417.21,6422.87,0],[-0.945745,0.324911,0],[0,0,1]] call _cv;

["Land_Cargo_Patrol_V3_F",[7404.62,6452,0],[-0.909046,-0.416696,0],[0,0,1]] call _cv;

["Land_Cargo_Patrol_V3_F",[7404.02,6380.42,0],[-0.424203,0.905567,0],[0,0,1]] call _cv;

["CamoNet_BLUFOR_F",[7409.86,6433.06,0],[0.402998,-0.915201,0],[0,0,1]] call _cv;

["Land_MedicalTent_01_NATO_generic_open_F",[7407.52,6441.25,0],[-0.909342,-0.41605,0],[0,0,1]] call _cv;

["Land_ConnectorTent_01_NATO_closed_F",[7401.33,6438.36,0.08912],[0.899586,0.436743,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7393.01,6434.78,0],[0.928121,0.372278,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7392.98,6434.87,2.14186],[0.928121,0.372278,0],[0,0,1]] call _cv;

["Land_WoodenTable_02_large_F",[7396.92,6434.31,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;

["Land_WoodenTable_02_large_F",[7398.77,6430.59,0],[0.411737,-0.911303,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7395.91,6428.11,0],[0.915629,0.402023,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7399.22,6425.55,0],[-0.384775,0.923011,0],[0,0,1]] call _cv;

_o = ["Land_FoodSacks_01_large_brown_F",[7412.61,6437.34,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;
[_o, 7] call ace_cargo_fnc_setSize;

_o = ["Land_FoodSacks_01_large_brown_F",[7411.11,6436.62,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;
[_o, 7] call ace_cargo_fnc_setSize;

["Land_WoodenTable_02_large_F",[7407.42,6431.67,0],[0.411737,-0.911303,0],[0,0,1]] call _cv;

["Land_WoodenTable_02_large_F",[7410.23,6432.94,0],[0.411737,-0.911303,0],[0,0,1]] call _cv;

["Land_WoodenTable_02_large_F",[7413.18,6434.13,0],[0.411737,-0.911303,0],[0,0,1]] call _cv;

["Land_WaterTank_04_F",[7398.56,6426.94,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;

_o = ["Land_PaperBox_01_open_water_F",[7402.67,6435.2,0],[0.716005,0.698096,0],[0,0,1]] call _cv;
[_o, 7] call ace_cargo_fnc_setSize;

_o = ["Land_WaterBottle_01_stack_F",[7406.15,6434.59,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;
[_o, 7] call ace_cargo_fnc_setSize;

["Land_WaterBottle_01_pack_F",[7406.21,6434.42,1.26],[0.571929,0.820303,0],[0,0,1]] call _cv;

["WaterSpill_01_Small_Old_F",[7398.65,6427.05,1.25131],[-0.910866,-0.412701,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7415.69,6430.55,0],[-0.426567,0.904456,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7410.53,6428.14,0],[-0.437887,0.89903,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7406.03,6427.94,0],[-0.797703,-0.603051,0],[0,0,1]] call _cv;

["Land_LampHalogen_F",[7394.5,6431.83,0],[-0.811321,0.584601,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7405.26,6447.56,0],[0.399806,-0.9166,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7397.71,6443.94,0],[0.427527,-0.904002,0],[0,0,1]] call _cv;

["Land_WoodenTable_02_large_F",[7395.28,6437.53,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;

["Land_MedicalTent_01_NATO_generic_open_F",[7368.36,6414.58,0],[-0.407446,0.913229,0],[0,0,1]] call _cv;

["Land_MedicalTent_01_NATO_generic_open_F",[7377.14,6418.79,0],[-0.411398,0.911456,0],[0,0,1]] call _cv;

["Land_MedicalTent_01_NATO_generic_open_F",[7371.55,6435.71,0],[-0.411398,0.911456,0],[0,0,1]] call _cv;

["Land_FieldToilet_F",[7356.53,6418.49,0.03],[-0.913259,-0.40738,0],[0,0,1]] call _cv;

["Land_FieldToilet_F",[7355.88,6419.74,0.03],[-0.91295,-0.40807,0],[0,0,1]] call _cv;

["Land_FieldToilet_F",[7355.45,6421.24,0.03],[-0.916552,-0.399916,0],[0,0,1]] call _cv;

["Land_GymRack_01_F",[7362.89,6413.2,0],[0.947937,0.318459,0],[0,0,1]] call _cv;

["Land_GymBench_01_F",[7364.37,6407.93,0],[0.399408,-0.916773,0],[0,0,1]] call _cv;

["Land_GymBench_01_F",[7360.42,6408.49,0],[-0.658748,-0.752363,0],[0,0,1]] call _cv;

["Land_GymRack_03_F",[7362.19,6406.4,0],[-0.519099,-0.854714,0],[0,0,1]] call _cv;

["Land_Bench_05_F",[7358.2,6412.54,0],[-0.909184,-0.416394,0],[0,0,1]] call _cv;

["Land_Bench_05_F",[7361.04,6415.65,0],[-0.248227,-0.968702,0],[0,0,1]] call _cv;

["Land_Sink_F",[7360.03,6421.48,0],[-0.91514,-0.403137,0],[0,0,1]] call _cv;

["Land_WaterTank_03_F",[7360.66,6420,0],[0.940625,0.339447,0],[0,0,1]] call _cv;

["Land_FMradio_F",[7357.86,6413.29,0],[0.982139,-0.188157,0],[0,0,1]] call _cv;

["Tire_Van_02_F",[7360.38,6410.81,0],[-0.420027,0.907512,0],[0,0,1]] call _cv;

_o = ["Land_HBarrier_Big_F",[7372.8,6408.81,2.14991],[0.437356,-0.899288,0],[0,0,1]] call _cv;
_o enableDynamicSimulation true;

["Land_HBarrier_Big_F",[7372.78,6408.79,0],[0.437356,-0.899288,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7365.39,6405.4,2.19349],[0.339264,-0.940691,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7365.36,6405.38,0],[0.339264,-0.940691,0],[0,0,1]] call _cv;

["Land_LampHalogen_F",[7369.13,6406.47,0],[-0.639515,0.768779,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7380.5,6412.54,2.15477],[-0.379887,0.925033,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7380.45,6412.6,0],[-0.379887,0.925033,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7384.08,6417.54,0],[-0.932022,-0.362402,0],[0,0,1]] call _cv;

["Land_Sink_F",[7398.59,6441.27,0],[0.431105,-0.902302,0],[0,0,1]] call _cv;

["Land_WaterTank_03_F",[7400.04,6441.96,0],[-0.36823,0.929735,0],[0,0,1]] call _cv;

_o = ["Land_MedicalTent_01_MTP_closed_F",[7394.64,6395.87,0],[-0.44056,0.897723,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_ConnectorTent_01_NATO_closed_F",[7391.59,6401.96,0.08912],[-0.446477,0.894795,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_MedicalTent_01_floor_dark_F",[7394.65,6395.92,0],[-0.4562,0.889877,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_IntravenStand_01_1bag_F",[7395.83,6401.07,0],[0.333658,0.942694,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Land_IntravenStand_01_2bags_F",[7391.44,6395.42,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Land_Stretcher_01_olive_F",[7392.28,6394.94,0],[0.89445,0.447168,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_olive_F",[7395.33,6399.9,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_olive_F",[7391.51,6396.25,0],[-0.88832,-0.459225,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_olive_F",[7397.36,6396.01,0],[0.901655,0.432457,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_olive_F",[7396.66,6397.6,0],[0.889523,0.45689,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["BloodSpray_01_Old_F",[7395.14,6399.23,0],[0.658037,-0.752986,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["BloodPool_01_Medium_Old_F",[7395.28,6399.43,0.500309],[-0.51498,0.857202,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["MedicalGarbage_01_Bandage_F",[7395.04,6399.47,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["MedicalGarbage_01_Gloves_F",[7395.48,6399.17,0.500309],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_folded_sand_F",[7399.46,6393.63,0],[-0.993609,0.112873,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_folded_sand_F",[7399.01,6393.39,0],[0.977831,-0.209394,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_folded_sand_F",[7398.44,6392.87,0],[-0.88814,-0.459573,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["MedicalGarbage_01_Bandage_F",[7395.48,6399.2,0.500309],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_PortableCabinet_01_bookcase_sand_F",[7389.91,6398.18,0],[-0.99009,-0.140437,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_PortableCabinet_01_medical_F",[7393.11,6391.59,0],[-0.906747,-0.421675,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Defibrillator_F",[7394.58,6400.24,0],[-0.896361,-0.443326,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;
[_o, 1] call ace_cargo_fnc_setSize;

_o = ["Land_IntravenStand_01_empty_F",[7392.87,6392.09,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["MedicalGarbage_01_1x1_v3_F",[7394.9,6399.94,0],[0.998379,-0.056911,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_FirstAidKit_01_closed_F",[7393.17,6391.02,0],[-0.906998,-0.421135,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_FirstAidKit_01_closed_F",[7393.46,6390.62,0],[-0.598895,-0.800827,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_EmergencyBlanket_01_stack_F",[7394.38,6390.85,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_EmergencyBlanket_02_stack_F",[7394.95,6391.12,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_EmergencyBlanket_01_discarded_F",[7396.6,6397.55,0.5],[0.884359,0.466808,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_EmergencyBlanket_01_F",[7392.86,6395.22,0.5],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Bodybag_01_folded_black_F",[7399.55,6394.23,1.31],[0.2198,-0.929848,0.295077],[0.880097,0.319494,0.351216]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_IntravenStand_01_2bags_F",[7397.06,6396.75,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Land_FirstAidKit_01_open_F",[7393.77,6391.27,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_PortableCabinet_01_closed_sand_F",[7390.7,6398.72,0],[-0.404194,0.914673,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

["Land_PortableDesk_01_sand_F",[7390.62,6396.65,0],[-0.887681,-0.460459,0],[0,0,1]] call _cv;

_o = ["Land_DeskChair_01_sand_F",[7390.42,6397.42,0.89],[-0.911552,-0.411184,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

["Land_HBarrier_Big_F",[7376.34,6438.94,0],[-0.923862,-0.382727,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7390.4,6390.47,0],[0.902674,0.430325,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7386.73,6398.2,0],[-0.927969,-0.372657,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7375.55,6404.54,0],[0.89867,0.438624,0],[0,0,1]] call _cv;

_o = ["Land_RepairDepot_01_tan_F",[7384.46,6371.61,0],[-0.419364,0.907818,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

["Land_Cargo_House_V3_F",[7387.29,6433.31,0],[0.906431,0.422354,0],[0,0,1]] call _cv;

["Land_TTowerSmall_1_F",[7387.99,6429.92,0],[0.981333,0.192318,0],[0,0,1]] call _cv;

["Land_Cargo_House_V3_F",[7405.6,6416.46,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Cargo_House_V3_F",[7399.35,6413.59,0],[-0.902661,-0.430353,0],[0,0,1]] call _cv;

_o = ["Box_NATO_Ammo_F",[7405.42,6413.5,0],[-0.120943,-0.992659,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Box_NATO_Wps_F",[7400.75,6412.7,0],[0.891531,0.45296,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Box_NATO_Equip_F",[7404.47,6417.39,0],[0.413515,-0.910497,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

["Land_HBarrier_5_F",[7410.47,6418.44,0],[-0.891722,-0.452584,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7405.57,6420.97,0],[-0.42858,0.903504,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7396.26,6416.42,0],[-0.42858,0.903504,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7394.46,6411.53,0],[-0.90327,-0.429073,0],[0,0,1]] call _cv;

["Land_WaterTower_01_F",[7401.82,6404.97,0],[-0.41561,0.909543,0],[0,0,1]] call _cv;

["WaterSpill_01_Medium_New_F",[7404.19,6405.71,0],[0.432956,-0.901415,0],[0,0,1]] call _cv;

["StorageBladder_02_water_sand_F",[7404.31,6399.04,0.035533],[0.9008,0.434235,0],[0,0,1]] call _cv;

["Land_LampHalogen_F",[7397.2,6406.44,0],[-0.583117,-0.812388,0],[0,0,1]] call _cv;

["Land_MedicalTent_01_NATO_generic_open_F",[7361.96,6431.5,0],[-0.411398,0.911456,0],[0,0,1]] call _cv;

_o = ["CargoNet_01_box_F",[7388.51,6400.66,0],[0.690309,-0.723514,0],[0,0,1]] call _cv;
[_o, 6] call ace_cargo_fnc_setSize;

["Land_HBarrierWall_corridor_F",[7407.07,6389.51,0],[0.39174,-0.920076,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7402.88,6394.52,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrierWall_corridor_F",[7407.94,6409.23,0],[-0.659488,-0.751715,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7408.42,6372.14,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7412.02,6373.91,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7415.63,6375.65,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7419.23,6377.39,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7422.83,6379.17,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7426.42,6380.95,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7411.07,6371.75,0],[-0.388059,0.921635,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7426.32,6379.13,0],[0.413117,-0.910678,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7418.77,6375.36,0],[0.413117,-0.910678,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_Corner_F",[7402.66,6375.32,0],[0.628283,-0.777985,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_Corner_F",[7405.86,6371.02,0],[-0.591941,0.805981,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7403.31,6370.28,0],[0.17675,0.984256,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7429.92,6382.64,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7433.51,6384.41,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7437.12,6386.15,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7440.73,6387.89,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7444.32,6389.67,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7447.92,6391.45,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7433.91,6382.77,0],[-0.388059,0.921635,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7449.63,6390.39,0],[0.413117,-0.910678,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7441.84,6386.62,0],[0.413117,-0.910678,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7449.21,6395.54,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7447.38,6399.11,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7445.6,6402.69,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7443.81,6406.28,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7441.98,6409.85,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7440.16,6413.42,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7450.5,6396.69,0],[-0.916427,-0.400201,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7442.51,6412.47,0],[0.905141,0.425112,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7446.53,6404.58,0],[0.905141,0.425112,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_Corner_F",[7450.25,6392.95,0],[-0.867851,-0.496824,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_Corner_F",[7438.85,6415.86,0],[0.259133,-0.965842,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7436.15,6416.62,0],[-0.367912,-0.929861,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7432.56,6418.05,0],[-0.367912,-0.929861,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7436.5,6418.1,0],[0.390608,0.920557,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7428.99,6419.43,0],[-0.345107,-0.938563,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7425.38,6420.76,0],[-0.345107,-0.938563,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7428.68,6421.11,0],[0.368024,0.929816,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_Corner_F",[7423.58,6422.26,0],[0.052783,-0.998606,0],[0,0,1]] call _cv;

["Land_HBarrier_1_F",[7422.22,6421.39,0],[-0.999949,-0.010133,0],[0,0,1]] call _cv;

_o = ["B_Slingload_01_Fuel_F",[7410.43,6384.31,0],[-0.415074,0.909788,0],[0,0,1]] call _cv;
[_o, 50] call ace_cargo_fnc_setSize;

_o = ["B_Slingload_01_Repair_F",[7411.89,6413.19,0],[-0.912982,-0.407999,0],[0,0,1]] call _cv;
[_o, 50] call ace_cargo_fnc_setSize;

_o = ["B_Slingload_01_Ammo_F",[7417.9,6415.86,0],[-0.904211,-0.427086,0],[0,0,1]] call _cv;
[_o, 50] call ace_cargo_fnc_setSize;

_o = ["Box_EAF_AmmoVeh_F",[7382.55,6376.82,0],[0.916362,0.40035,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Box_EAF_AmmoVeh_F",[7381.93,6378.24,0],[0.916362,0.40035,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

["Land_HelipadSquare_F",[7430.23,6400.22,0],[-0.884506,-0.466529,0],[0,0,1]] call _cv;

// Total: 283 objects (all createVehicle for ATL positioning)