/*
    scripts\groundMissions\fn_fobHunting.sqf
    GROUND MISSION: FOB Hunting

    Players are tasked with infiltrating a heavily defended enemy FOB and
    destroying all four supply asset types:
        - B_Slingload_01_Repair_F
        - B_Slingload_01_Ammo_F
        - B_Slingload_01_Fuel_F
        - Box_EAF_AmmoVeh_F x2
    Reputation reward: 15-21 (random on mission start)

    The FOB is located at a fixed position on the map. A garrison of OPFOR
    infantry defends the compound. All assets must be destroyed within the
    time limit for full mission success.
*/
if (!isServer) exitWith {};

diag_log "[GROUND-FOB] Setting up FOB Hunting mission...";

// =====================================================
// 1. SETTINGS
// =====================================================
private _hardcodedCenter = [7396, 6411, 0];  // Centre of the FOB composition (editor export origin)
private _zoneCenter      = [0, 0, 0];       // Zone centre (marker/task position)
private _fobCenter       = _hardcodedCenter; // Actual FOB position (offset inside zone)
private _searchRadius = 200;               // Radius for target object search
private _zoneRadius   = 300;               // Marker zone radius
private _timeout      = 7200;             // 2 hours
private _cleanupDelay = 120;              // Seconds before entity despawn after mission end

// Reputation awarded on full destruction (15-21 random)
private _repPerSlingload = 5;   // used for target tracking only
private _repPerAmmoBox   = 3;   // used for target tracking only
private _repReward = 15 + floor (random 7);  // 15-21 rep

// =====================================================
// 2. SPAWN THE FOB BUILDING
// =====================================================
diag_log "[GROUND-FOB] Creating FOB building objects...";
// ---- inlined FOB building composition (Domo v0.9 export) ----
// =====================================================
// FOB BUILDING COMPOSITION (editor export, VR map, centre ~7396,6411)
// All positions are absolute; relocated via delta-shift below.
// =====================================================
// Auto-generated composition from editor export
// Generated by parse_export.py

if (isNil "DYN_ground_enemies")     then { DYN_ground_enemies = [] };
if (isNil "DYN_ground_enemyVehs")   then { DYN_ground_enemyVehs = [] };
if (isNil "DYN_ground_enemyGroups") then { DYN_ground_enemyGroups = [] };
if (isNil "DYN_ground_objects")     then { DYN_ground_objects = [] };
if (isNil "DYN_ground_tasks")       then { DYN_ground_tasks = [] };
if (isNil "DYN_ground_markers")     then { DYN_ground_markers = [] };

// Helper: create object with rotation (all use createVehicle for ATL positioning)
private _cv = {
    params ["_t","_p","_d","_u"];
    private _o = createVehicle [_t,_p,[],0,"CAN_COLLIDE"];
    _o setPosATL [_p select 0, _p select 1, 0];
    _o setVectorDirAndUp [_d,_u];
    DYN_ground_objects pushBack _o;
    _o
};

private _o = objNull;

["Land_Mil_WallBig_4m_F",[7367.05,6392.27,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7368.8,6388.66,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7370.51,6385.04,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7372.23,6381.42,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7373.98,6377.81,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7375.74,6374.2,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7377.45,6370.58,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7379.2,6366.98,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7381.71,6366.25,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7385.34,6367.94,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7388.99,6369.59,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7392.64,6371.25,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7396.28,6372.93,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7399.92,6374.62,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7404.41,6373.29,0],[0.925095,0.379736,0],[0,0,1]] call _cv;

["Land_BarGate_F",[7355.12,6394.56,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_HBarrierTower_F",[7355.78,6386.06,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_HBarrierTower_F",[7348.22,6401.83,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7362.3,6386.28,0],[0.367001,-0.930221,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7366.64,6389.62,0],[0.924304,0.381656,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7348.85,6429.75,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7350.6,6426.15,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7352.31,6422.52,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7354.03,6418.9,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7355.78,6415.29,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7357.53,6411.69,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7359.24,6408.07,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7360.99,6404.46,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7358.49,6406,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7375.18,6443.59,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7371.52,6441.95,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7367.85,6440.35,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7364.18,6438.75,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7360.51,6437.11,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7356.86,6435.47,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7353.18,6433.87,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7349.53,6432.23,0],[0.400761,-0.916183,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7407.87,6380.2,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7406.15,6383.81,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7402.78,6391.08,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7401.05,6394.7,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7399.33,6398.32,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7397.64,6401.95,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7395.92,6405.57,0],[-0.906453,-0.422307,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7396.78,6408.37,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7400.41,6410.06,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7407.71,6413.36,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7411.35,6415.05,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7414.98,6416.74,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7418.64,6418.39,0],[-0.413285,0.910602,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7422.09,6420.33,0],[-0.546163,0.837679,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7404.59,6455.94,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7400.9,6454.37,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7397.2,6452.85,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7393.5,6451.32,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7389.8,6449.75,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7386.11,6448.19,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7382.41,6446.66,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7378.72,6445.09,0],[0.382557,-0.923932,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7421.92,6423.95,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7420.29,6427.42,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7418.65,6430.9,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7417.01,6434.39,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7415.38,6437.88,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7413.73,6441.33,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7412.09,6444.81,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7410.46,6448.29,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7408.82,6451.77,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7407.18,6455.25,0],[-0.90483,-0.425773,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7354.81,6413.69,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7351.1,6421.53,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7347.38,6429.1,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7374.28,6444.65,0],[0.377206,-0.926129,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7366.47,6441.22,0],[0.377206,-0.926129,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7358.51,6437.77,0],[0.377206,-0.926129,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7350.83,6434.29,0],[0.377206,-0.926129,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7382.2,6448.16,0],[-0.361168,0.932501,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7390.07,6451.46,0],[-0.361168,0.932501,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7398.08,6454.78,0],[-0.361168,0.932501,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7403.94,6457.31,0],[-0.361168,0.932501,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7420.7,6430.76,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7417.02,6438.45,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7413.31,6446.29,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7409.59,6453.86,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7422.53,6426.8,0],[0.901159,0.43349,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7383.86,6365.42,0],[-0.351307,0.93626,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7377.63,6366.48,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7373.92,6374.32,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7370.2,6381.89,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7391.67,6368.86,0],[-0.413415,0.910543,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7398.67,6370.59,0],[-0.008841,0.999961,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7408.33,6382.84,0],[-0.920247,-0.391338,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7399.16,6402.12,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7401.09,6398.3,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7400.08,6408.01,0],[-0.403347,0.915047,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7352.8,6406.35,0],[0.372911,-0.927867,0],[0,0,1]] call _cv;

_o = ["Land_Razorwire_F",[7343.16,6400.14,0],[0.90327,0.429073,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_Razorwire_F",[7351.74,6383.12,0],[0.90327,0.429073,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_Razorwire_F",[7356.71,6381.91,0],[0.427332,-0.904095,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_Razorwire_F",[7362.94,6384.72,0],[-0.40814,0.91292,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_Razorwire_F",[7345.34,6405.03,0],[-0.40814,0.91292,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_Razorwire_F",[7352.19,6408.26,0],[-0.40814,0.91292,0],[0,0,1]] call _cv;
_o allowDamage false;

["Land_CncBarrierMedium4_F",[7353.15,6389.26,0],[0.422665,-0.906286,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium4_F",[7348.79,6397.67,0],[0.422665,-0.906286,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7358.15,6402.11,0],[0.405091,-0.914277,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7356.46,6401.34,0],[0.405091,-0.914277,0],[0,0,1]] call _cv;

["Land_CampingTable_small_F",[7356.14,6405.39,0.08912],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_ConnectorTent_01_NATO_closed_F",[7355.51,6404.24,0.08912],[0.910646,0.413187,0],[0,0,1]] call _cv;

_o = ["Land_CzechHedgehog_01_new_F",[7344.73,6396.49,0],[0.90327,0.429073,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7349.37,6387.06,0],[0.558837,-0.829277,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7341.16,6403.51,0],[0.610151,0.792285,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7354.66,6409.65,0],[0.610151,0.792285,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7348.35,6406.72,0],[0.610151,0.792285,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7353.24,6379.92,0],[-0.279131,0.960253,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7359.26,6382.87,0],[0.610151,0.792285,0],[0,0,1]] call _cv;
_o allowDamage false;

_o = ["Land_CzechHedgehog_01_new_F",[7365.94,6385.79,0],[0.610151,0.792285,0],[0,0,1]] call _cv;
_o allowDamage false;

["Land_CncBarrierMedium_F",[7352.99,6399.62,0],[0.421256,-0.906942,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7351.83,6400.21,0],[0.908492,0.417902,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7360.55,6392.59,0],[-0.405035,0.914301,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7362.22,6393.37,0],[-0.435883,0.900003,0],[0,0,1]] call _cv;

["Land_CncBarrierMedium_F",[7363.38,6392.8,0],[-0.901608,-0.432555,0],[0,0,1]] call _cv;

["Land_Cargo_Patrol_V3_F",[7352.59,6429.74,0],[0.420555,-0.907267,0],[0,0,1]] call _cv;

["Land_Cargo_Patrol_V3_F",[7417.21,6422.87,0],[-0.945745,0.324911,0],[0,0,1]] call _cv;

["Land_Cargo_Patrol_V3_F",[7404.62,6452,0],[-0.909046,-0.416696,0],[0,0,1]] call _cv;

["Land_Cargo_Patrol_V3_F",[7404.02,6380.42,0],[-0.424203,0.905567,0],[0,0,1]] call _cv;

["CamoNet_BLUFOR_F",[7409.86,6433.06,0],[0.402998,-0.915201,0],[0,0,1]] call _cv;

["Land_MedicalTent_01_NATO_generic_open_F",[7407.52,6441.25,0],[-0.909342,-0.41605,0],[0,0,1]] call _cv;

["Land_ConnectorTent_01_NATO_closed_F",[7401.33,6438.36,0.08912],[0.899586,0.436743,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7393.01,6434.78,0],[0.928121,0.372278,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7392.98,6434.87,2.14186],[0.928121,0.372278,0],[0,0,1]] call _cv;

["Land_WoodenTable_02_large_F",[7396.92,6434.31,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;

["Land_WoodenTable_02_large_F",[7398.77,6430.59,0],[0.411737,-0.911303,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7395.91,6428.11,0],[0.915629,0.402023,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7399.22,6425.55,0],[-0.384775,0.923011,0],[0,0,1]] call _cv;

_o = ["Land_FoodSacks_01_large_brown_F",[7412.61,6437.34,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;
[_o, 7] call ace_cargo_fnc_setSize;

_o = ["Land_FoodSacks_01_large_brown_F",[7411.11,6436.62,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;
[_o, 7] call ace_cargo_fnc_setSize;

["Land_WoodenTable_02_large_F",[7407.42,6431.67,0],[0.411737,-0.911303,0],[0,0,1]] call _cv;

["Land_WoodenTable_02_large_F",[7410.23,6432.94,0],[0.411737,-0.911303,0],[0,0,1]] call _cv;

["Land_WoodenTable_02_large_F",[7413.18,6434.13,0],[0.411737,-0.911303,0],[0,0,1]] call _cv;

["Land_WaterTank_04_F",[7398.56,6426.94,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;

_o = ["Land_PaperBox_01_open_water_F",[7402.67,6435.2,0],[0.716005,0.698096,0],[0,0,1]] call _cv;
[_o, 7] call ace_cargo_fnc_setSize;

_o = ["Land_WaterBottle_01_stack_F",[7406.15,6434.59,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;
[_o, 7] call ace_cargo_fnc_setSize;

["Land_WaterBottle_01_pack_F",[7406.21,6434.42,1.26],[0.571929,0.820303,0],[0,0,1]] call _cv;

["WaterSpill_01_Small_Old_F",[7398.65,6427.05,1.25131],[-0.910866,-0.412701,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7415.69,6430.55,0],[-0.426567,0.904456,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7410.53,6428.14,0],[-0.437887,0.89903,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7406.03,6427.94,0],[-0.797703,-0.603051,0],[0,0,1]] call _cv;

["Land_LampHalogen_F",[7394.5,6431.83,0],[-0.811321,0.584601,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7405.26,6447.56,0],[0.399806,-0.9166,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7397.71,6443.94,0],[0.427527,-0.904002,0],[0,0,1]] call _cv;

["Land_WoodenTable_02_large_F",[7395.28,6437.53,0],[-0.910866,-0.412701,0],[0,0,1]] call _cv;

["Land_MedicalTent_01_NATO_generic_open_F",[7368.36,6414.58,0],[-0.407446,0.913229,0],[0,0,1]] call _cv;

["Land_MedicalTent_01_NATO_generic_open_F",[7377.14,6418.79,0],[-0.411398,0.911456,0],[0,0,1]] call _cv;

["Land_MedicalTent_01_NATO_generic_open_F",[7371.55,6435.71,0],[-0.411398,0.911456,0],[0,0,1]] call _cv;

["Land_FieldToilet_F",[7356.53,6418.49,0.03],[-0.913259,-0.40738,0],[0,0,1]] call _cv;

["Land_FieldToilet_F",[7355.88,6419.74,0.03],[-0.91295,-0.40807,0],[0,0,1]] call _cv;

["Land_FieldToilet_F",[7355.45,6421.24,0.03],[-0.916552,-0.399916,0],[0,0,1]] call _cv;

["Land_GymRack_01_F",[7362.89,6413.2,0],[0.947937,0.318459,0],[0,0,1]] call _cv;

["Land_GymBench_01_F",[7364.37,6407.93,0],[0.399408,-0.916773,0],[0,0,1]] call _cv;

["Land_GymBench_01_F",[7360.42,6408.49,0],[-0.658748,-0.752363,0],[0,0,1]] call _cv;

["Land_GymRack_03_F",[7362.19,6406.4,0],[-0.519099,-0.854714,0],[0,0,1]] call _cv;

["Land_Bench_05_F",[7358.2,6412.54,0],[-0.909184,-0.416394,0],[0,0,1]] call _cv;

["Land_Bench_05_F",[7361.04,6415.65,0],[-0.248227,-0.968702,0],[0,0,1]] call _cv;

["Land_Sink_F",[7360.03,6421.48,0],[-0.91514,-0.403137,0],[0,0,1]] call _cv;

["Land_WaterTank_03_F",[7360.66,6420,0],[0.940625,0.339447,0],[0,0,1]] call _cv;

["Land_FMradio_F",[7357.86,6413.29,0],[0.982139,-0.188157,0],[0,0,1]] call _cv;

["Tire_Van_02_F",[7360.38,6410.81,0],[-0.420027,0.907512,0],[0,0,1]] call _cv;

_o = ["Land_HBarrier_Big_F",[7372.8,6408.81,2.14991],[0.437356,-0.899288,0],[0,0,1]] call _cv;
_o enableDynamicSimulation true;

["Land_HBarrier_Big_F",[7372.78,6408.79,0],[0.437356,-0.899288,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7365.39,6405.4,2.19349],[0.339264,-0.940691,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7365.36,6405.38,0],[0.339264,-0.940691,0],[0,0,1]] call _cv;

["Land_LampHalogen_F",[7369.13,6406.47,0],[-0.639515,0.768779,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7380.5,6412.54,2.15477],[-0.379887,0.925033,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7380.45,6412.6,0],[-0.379887,0.925033,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7384.08,6417.54,0],[-0.932022,-0.362402,0],[0,0,1]] call _cv;

["Land_Sink_F",[7398.59,6441.27,0],[0.431105,-0.902302,0],[0,0,1]] call _cv;

["Land_WaterTank_03_F",[7400.04,6441.96,0],[-0.36823,0.929735,0],[0,0,1]] call _cv;

_o = ["Land_MedicalTent_01_MTP_closed_F",[7394.64,6395.87,0],[-0.44056,0.897723,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_ConnectorTent_01_NATO_closed_F",[7391.59,6401.96,0.08912],[-0.446477,0.894795,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_MedicalTent_01_floor_dark_F",[7394.65,6395.92,0],[-0.4562,0.889877,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_IntravenStand_01_1bag_F",[7395.83,6401.07,0],[0.333658,0.942694,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Land_IntravenStand_01_2bags_F",[7391.44,6395.42,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Land_Stretcher_01_olive_F",[7392.28,6394.94,0],[0.89445,0.447168,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_olive_F",[7395.33,6399.9,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_olive_F",[7391.51,6396.25,0],[-0.88832,-0.459225,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_olive_F",[7397.36,6396.01,0],[0.901655,0.432457,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_olive_F",[7396.66,6397.6,0],[0.889523,0.45689,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["BloodSpray_01_Old_F",[7395.14,6399.23,0],[0.658037,-0.752986,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["BloodPool_01_Medium_Old_F",[7395.28,6399.43,0.500309],[-0.51498,0.857202,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["MedicalGarbage_01_Bandage_F",[7395.04,6399.47,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["MedicalGarbage_01_Gloves_F",[7395.48,6399.17,0.500309],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_folded_sand_F",[7399.46,6393.63,0],[-0.993609,0.112873,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_folded_sand_F",[7399.01,6393.39,0],[0.977831,-0.209394,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Stretcher_01_folded_sand_F",[7398.44,6392.87,0],[-0.88814,-0.459573,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["MedicalGarbage_01_Bandage_F",[7395.48,6399.2,0.500309],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_PortableCabinet_01_bookcase_sand_F",[7389.91,6398.18,0],[-0.99009,-0.140437,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_PortableCabinet_01_medical_F",[7393.11,6391.59,0],[-0.906747,-0.421675,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Defibrillator_F",[7394.58,6400.24,0],[-0.896361,-0.443326,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;
[_o, 1] call ace_cargo_fnc_setSize;

_o = ["Land_IntravenStand_01_empty_F",[7392.87,6392.09,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["MedicalGarbage_01_1x1_v3_F",[7394.9,6399.94,0],[0.998379,-0.056911,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_FirstAidKit_01_closed_F",[7393.17,6391.02,0],[-0.906998,-0.421135,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_FirstAidKit_01_closed_F",[7393.46,6390.62,0],[-0.598895,-0.800827,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_EmergencyBlanket_01_stack_F",[7394.38,6390.85,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_EmergencyBlanket_02_stack_F",[7394.95,6391.12,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_EmergencyBlanket_01_discarded_F",[7396.6,6397.55,0.5],[0.884359,0.466808,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_EmergencyBlanket_01_F",[7392.86,6395.22,0.5],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_Bodybag_01_folded_black_F",[7399.55,6394.23,1.31],[0.2198,-0.929848,0.295077],[0.880097,0.319494,0.351216]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_IntravenStand_01_2bags_F",[7397.06,6396.75,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Land_FirstAidKit_01_open_F",[7393.77,6391.27,0],[0.462938,-0.886391,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

_o = ["Land_PortableCabinet_01_closed_sand_F",[7390.7,6398.72,0],[-0.404194,0.914673,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

["Land_PortableDesk_01_sand_F",[7390.62,6396.65,0],[-0.887681,-0.460459,0],[0,0,1]] call _cv;

_o = ["Land_DeskChair_01_sand_F",[7390.42,6397.42,0.89],[-0.911552,-0.411184,0],[0,0,1]] call _cv;
_o allowDamage false;
_o enableSimulation false;

["Land_HBarrier_Big_F",[7376.34,6438.94,0],[-0.923862,-0.382727,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7390.4,6390.47,0],[0.902674,0.430325,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7386.73,6398.2,0],[-0.927969,-0.372657,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7375.55,6404.54,0],[0.89867,0.438624,0],[0,0,1]] call _cv;

_o = ["Land_RepairDepot_01_tan_F",[7384.46,6371.61,0],[-0.419364,0.907818,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

["Land_Cargo_House_V3_F",[7387.29,6433.31,0],[0.906431,0.422354,0],[0,0,1]] call _cv;

["Land_TTowerSmall_1_F",[7387.99,6429.92,0],[0.981333,0.192318,0],[0,0,1]] call _cv;

["Land_Cargo_House_V3_F",[7405.6,6416.46,0],[0.90327,0.429073,0],[0,0,1]] call _cv;

["Land_Cargo_House_V3_F",[7399.35,6413.59,0],[-0.902661,-0.430353,0],[0,0,1]] call _cv;

_o = ["Box_NATO_Ammo_F",[7405.42,6413.5,0],[-0.120943,-0.992659,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Box_NATO_Wps_F",[7400.75,6412.7,0],[0.891531,0.45296,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Box_NATO_Equip_F",[7404.47,6417.39,0],[0.413515,-0.910497,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

["Land_HBarrier_5_F",[7410.47,6418.44,0],[-0.891722,-0.452584,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7405.57,6420.97,0],[-0.42858,0.903504,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7396.26,6416.42,0],[-0.42858,0.903504,0],[0,0,1]] call _cv;

["Land_HBarrier_5_F",[7394.46,6411.53,0],[-0.90327,-0.429073,0],[0,0,1]] call _cv;

["Land_WaterTower_01_F",[7401.82,6404.97,0],[-0.41561,0.909543,0],[0,0,1]] call _cv;

["WaterSpill_01_Medium_New_F",[7404.19,6405.71,0],[0.432956,-0.901415,0],[0,0,1]] call _cv;

["StorageBladder_02_water_sand_F",[7404.31,6399.04,0.035533],[0.9008,0.434235,0],[0,0,1]] call _cv;

["Land_LampHalogen_F",[7397.2,6406.44,0],[-0.583117,-0.812388,0],[0,0,1]] call _cv;

["Land_MedicalTent_01_NATO_generic_open_F",[7361.96,6431.5,0],[-0.411398,0.911456,0],[0,0,1]] call _cv;

_o = ["CargoNet_01_box_F",[7388.51,6400.66,0],[0.690309,-0.723514,0],[0,0,1]] call _cv;
[_o, 6] call ace_cargo_fnc_setSize;

["Land_HBarrierWall_corridor_F",[7407.07,6389.51,0],[0.39174,-0.920076,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7402.88,6394.52,0],[-0.913522,-0.406789,0],[0,0,1]] call _cv;

["Land_HBarrierWall_corridor_F",[7407.94,6409.23,0],[-0.659488,-0.751715,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7408.42,6372.14,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7412.02,6373.91,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7415.63,6375.65,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7419.23,6377.39,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7422.83,6379.17,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7426.42,6380.95,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7411.07,6371.75,0],[-0.388059,0.921635,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7426.32,6379.13,0],[0.413117,-0.910678,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7418.77,6375.36,0],[0.413117,-0.910678,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_Corner_F",[7402.66,6375.32,0],[0.628283,-0.777985,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_Corner_F",[7405.86,6371.02,0],[-0.591941,0.805981,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7403.31,6370.28,0],[0.17675,0.984256,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7429.92,6382.64,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7433.51,6384.41,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7437.12,6386.15,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7440.73,6387.89,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7444.32,6389.67,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7447.92,6391.45,0],[-0.435329,0.900272,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7433.91,6382.77,0],[-0.388059,0.921635,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7449.63,6390.39,0],[0.413117,-0.910678,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7441.84,6386.62,0],[0.413117,-0.910678,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7449.21,6395.54,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7447.38,6399.11,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7445.6,6402.69,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7443.81,6406.28,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7441.98,6409.85,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7440.16,6413.42,0],[-0.894442,-0.447185,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7450.5,6396.69,0],[-0.916427,-0.400201,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7442.51,6412.47,0],[0.905141,0.425112,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7446.53,6404.58,0],[0.905141,0.425112,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_Corner_F",[7450.25,6392.95,0],[-0.867851,-0.496824,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_Corner_F",[7438.85,6415.86,0],[0.259133,-0.965842,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7436.15,6416.62,0],[-0.367912,-0.929861,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7432.56,6418.05,0],[-0.367912,-0.929861,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7436.5,6418.1,0],[0.390608,0.920557,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7428.99,6419.43,0],[-0.345107,-0.938563,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_4m_F",[7425.38,6420.76,0],[-0.345107,-0.938563,0],[0,0,1]] call _cv;

["Land_HBarrier_Big_F",[7428.68,6421.11,0],[0.368024,0.929816,0],[0,0,1]] call _cv;

["Land_Mil_WallBig_Corner_F",[7423.58,6422.26,0],[0.052783,-0.998606,0],[0,0,1]] call _cv;

["Land_HBarrier_1_F",[7422.22,6421.39,0],[-0.999949,-0.010133,0],[0,0,1]] call _cv;

_o = ["B_Slingload_01_Fuel_F",[7410.43,6384.31,0],[-0.415074,0.909788,0],[0,0,1]] call _cv;
[_o, 50] call ace_cargo_fnc_setSize;

_o = ["B_Slingload_01_Repair_F",[7411.89,6413.19,0],[-0.912982,-0.407999,0],[0,0,1]] call _cv;
[_o, 50] call ace_cargo_fnc_setSize;

_o = ["B_Slingload_01_Ammo_F",[7417.9,6415.86,0],[-0.904211,-0.427086,0],[0,0,1]] call _cv;
[_o, 50] call ace_cargo_fnc_setSize;

_o = ["Box_EAF_AmmoVeh_F",[7382.55,6376.82,0],[0.916362,0.40035,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

_o = ["Box_EAF_AmmoVeh_F",[7381.93,6378.24,0],[0.916362,0.40035,0],[0,0,1]] call _cv;
[_o, 2] call ace_cargo_fnc_setSize;

["Land_HelipadSquare_F",[7430.23,6400.22,0],[-0.884506,-0.466529,0],[0,0,1]] call _cv;

// Total: 283 objects (all createVehicle for ATL positioning)


// Snapshot all created objects for relocation and cleanup
private _objects = +DYN_ground_objects;

// Hide objects at their hardcoded position until relocation is done
// (prevents the FOB briefly appearing at the editor-export origin, which
//  may be in the ocean on Altis)
{ if (!isNull _x) then { _x hideObjectGlobal true } } forEach _objects;

// Track buildings where garrison will spawn (towers, cargo buildings, open tents)
private _spawnBuildings = _objects select {
    typeOf _x in [
        "Land_HBarrierTower_F", "Land_Cargo_Patrol_V3_F", "Land_Cargo_House_V3_F",
        "Land_MedicalTent_01_NATO_generic_open_F"
    ]
};

// =====================================================
// DYNAMIC POSITIONING — find zone centre, then offset FOB inside
// =====================================================
private _basePos  = getMarkerPos "respawn_west";
private _aoCenter = missionNamespace getVariable ["DYN_AO_center", [0,0,0]];

// Step 1: find a valid zone centre (same as other ground missions)
for "_attempt" from 1 to 150 do {
    private _testPos = [_basePos, 2500 + random 10000, random 360] call DYN_fnc_posOffset;

    if (surfaceIsWater _testPos) then { continue };
    if (getTerrainHeightASL _testPos < 1) then { continue };
    if !(_aoCenter isEqualTo [0,0,0]) then {
        if (_testPos distance2D _aoCenter < 1000) then { continue };
    };

    // Basic flatness check — reject steep slopes
    private _heights = [0, 90, 180, 270] apply {
        getTerrainHeightASL ([_testPos, 60, _x] call DYN_fnc_posOffset)
    };
    if ((selectMax _heights) - (selectMin _heights) > 10) then { continue };

    _zoneCenter = _testPos;
    break;
};

if (surfaceIsWater _zoneCenter) exitWith {
    diag_log "[GROUND-FOB] ERROR: No valid land position found. Aborting.";
    { if (!isNull _x) then { deleteVehicle _x } } forEach _objects;
    DYN_ground_active = false;
};

// Step 2: offset the FOB randomly within the zone (retry up to 20 times to avoid water)
_fobCenter = _zoneCenter;
for "_fobAttempt" from 1 to 20 do {
    private _candidate = [_zoneCenter, 30 + random (_zoneRadius - 80), random 360] call DYN_fnc_posOffset;
    if (surfaceIsWater _candidate) then { continue };
    if (getTerrainHeightASL _candidate < 1) then { continue };
    _fobCenter = _candidate;
    break;
};
diag_log format ["[GROUND-FOB] Zone centre: %1  FOB offset to: %2", _zoneCenter, _fobCenter];

// Protect target objects from spawn-relocation damage
private _targetTypes = ["B_Slingload_01_Repair_F", "B_Slingload_01_Ammo_F", "B_Slingload_01_Fuel_F", "Box_EAF_AmmoVeh_F"];
{ if (!isNull _x && {typeOf _x in _targetTypes}) then { _x allowDamage false } } forEach _objects;

// Shift every building object from its hardcoded position to the FOB position
private _delta = [
    (_fobCenter select 0) - (_hardcodedCenter select 0),
    (_fobCenter select 1) - (_hardcodedCenter select 1),
    0
];
{ if (!isNull _x) then {
    private _p = getPosATL _x vectorAdd _delta;
    _x setPosATL [_p select 0, _p select 1, 0];
} } forEach _objects;
diag_log format ["[GROUND-FOB] FOB relocated to %1", _fobCenter];

// Allow object initialisation to settle
sleep 2;

// Unhide objects now that they are at the correct position
{ if (!isNull _x) then { _x hideObjectGlobal false } } forEach _objects;

// Re-enable damage on target objects now that relocation is done
{ if (!isNull _x && {typeOf _x in _targetTypes}) then { _x allowDamage true } } forEach _objects;

// Heal targets to full HP after 10 s — relocation/terrain settling can cause
// phantom damage (~11 %) which risks accidental destruction during the mission.
private _healTargets = _objects select { !isNull _x && {typeOf _x in _targetTypes} };
_healTargets spawn {
    sleep 10;
    {
        if (!isNull _x) then {
            _x setDamage [0, true];  // true = global (all clients)
            diag_log format ["[GROUND-FOB] Healed %1 to full HP after spawn settle.", typeOf _x];
        };
    } forEach _this;
};

// Disable damage on military walls so they can't be destroyed
private _wallTypes = ["Land_Mil_WallBig_4m_F", "Land_Mil_WallBig_Corner_F", "Land_HBarrierWall_corridor_F"];
{ if (!isNull _x && {typeOf _x in _wallTypes}) then { _x allowDamage false } } forEach _objects;

// Collect all FOB building objects for cleanup at mission end
private _fobObjects = [];
{ if (!isNull _x) then { _fobObjects pushBack _x } } forEach _objects;

diag_log format ["[GROUND-FOB] Building SQF created %1 objects.", count _fobObjects];

// Disable simulation on static props that don't need physics
private _simKeepTypes = [
    "B_Slingload_01_Repair_F", "B_Slingload_01_Ammo_F", "B_Slingload_01_Fuel_F",
    "Box_EAF_AmmoVeh_F",
    "Land_HBarrierTower_F", "Land_Cargo_Patrol_V3_F", "Land_Cargo_House_V3_F",
    "Land_MedicalTent_01_NATO_generic_open_F"
];
{
    if (!isNull _x && {!(typeOf _x in _simKeepTypes)}) then {
        _x enableSimulationGlobal false;
    };
} forEach _fobObjects;
diag_log format ["[GROUND-FOB] Simulation disabled on %1 static props.", count _fobObjects - count (_fobObjects select { typeOf _x in _simKeepTypes })];

// =====================================================
// 3. LOCATE TARGET OBJECTS
// =====================================================
private _repairPod = objNull;
private _ammoPod   = objNull;
private _fuelPod   = objNull;
private _ammoBoxes = [];

{
    switch (typeOf _x) do {
        case "B_Slingload_01_Repair_F": { _repairPod = _x };
        case "B_Slingload_01_Ammo_F":   { _ammoPod   = _x };
        case "B_Slingload_01_Fuel_F":   { _fuelPod   = _x };
        case "Box_EAF_AmmoVeh_F":       { _ammoBoxes pushBack _x };
    };
} forEach nearestObjects [_fobCenter,
    ["B_Slingload_01_Repair_F",
     "B_Slingload_01_Ammo_F",
     "B_Slingload_01_Fuel_F",
     "Box_EAF_AmmoVeh_F"],
    _searchRadius];

// Validate all required targets were found
if (isNull _repairPod || isNull _ammoPod || isNull _fuelPod || count _ammoBoxes < 1) exitWith {
    diag_log "[GROUND-FOB] ERROR: One or more target objects not found. Aborting.";
    { if (!isNull _x) then { deleteVehicle _x } } forEach _fobObjects;
    DYN_ground_active = false;
};

diag_log format [
    "[GROUND-FOB] Targets confirmed - Repair: %1  Ammo: %2  Fuel: %3  AmmoBoxes: %4",
    !isNull _repairPod, !isNull _ammoPod, !isNull _fuelPod, count _ammoBoxes
];

// =====================================================
// 4. SPAWN ENEMY GARRISON
// =====================================================
// Garrison spawns inside spawn buildings (towers, patrol posts, cargo houses)
// plus an inner patrol, an outer patrol, and static MG posts.

private _infantryTypes = [
    "CUP_O_RU_Soldier_Ratnik_Autumn",
    "CUP_O_RU_Soldier_SL_Ratnik_Autumn",
    "CUP_O_RU_Soldier_AR_Ratnik_Autumn",
    "CUP_O_RU_Soldier_MG_Ratnik_Autumn",
    "CUP_O_RU_Soldier_GL_Ratnik_Autumn",
    "CUP_O_RU_Soldier_Marksman_Ratnik_Autumn",
    "CUP_O_RU_Soldier_LAT_Ratnik_Autumn"
];

// Garrison units that start locked in place — unlocked when players breach the FOB
private _garrisonUnits = [];

// --- Building garrison: place units inside each spawn building ---
{
    private _bldg = _x;
    private _bldgPos = getPosATL _bldg;
    private _bldgType = typeOf _bldg;

    // Towers get 3, tents get 3-4, cargo buildings get 5-6
    private _grpSize = switch (true) do {
        case (_bldgType == "Land_HBarrierTower_F"):                         { 3 };
        case (_bldgType == "Land_MedicalTent_01_NATO_generic_open_F"):      { 3 + floor random 2 };
        default                                                             { 5 + floor random 2 };
    };
    private _grp = createGroup east;

    // Get building positions; fall back to building centre
    private _bldgPositions = _bldg buildingPos -1;

    // For HBarrier towers, buildingPos returns ground-level interior slots.
    // Override with the observation-platform height (~6.5 m ATL) so units
    // actually stand on the planks instead of clipping inside the base.
    private _useTowerOverride = (_bldgType == "Land_HBarrierTower_F");

    for "_i" from 1 to _grpSize do {
        private _unitPos = if (_useTowerOverride) then {
            // Spread units around the tower centre on the platform
            private _off = [_bldgPos, 1 + random 1.5, _i * (360 / _grpSize)] call DYN_fnc_posOffset;
            [_off select 0, _off select 1, 6.5]
        } else {
            if (count _bldgPositions > 0) then {
                _bldgPositions select (_i mod count _bldgPositions)
            } else {
                [_bldgPos, 1 + random 2, random 360] call DYN_fnc_posOffset
            }
        };

        private _unit = _grp createUnit [selectRandom _infantryTypes, _unitPos, [], 0, "NONE"];
        if (!isNull _unit) then {
            _unit setPosATL _unitPos;
            _unit allowFleeing 0.1;
            _unit setSkill ["aimingAccuracy", 0.40 + random 0.35];
            _unit setSkill ["aimingShake",    0.45 + random 0.30];
            _unit setSkill ["aimingSpeed",    0.45 + random 0.30];
            _unit setSkill ["spotDistance",   0.70 + random 0.30];
            _unit setSkill ["spotTime",       0.65 + random 0.30];
            _unit setSkill ["courage",        0.75 + random 0.25];
            // Lock in place until players breach the FOB (re-enabled by monitor loop)
            _unit disableAI "MOVE";
            _unit disableAI "PATH";
            _unit disableAI "AUTOCOMBAT";
            DYN_ground_enemies pushBack _unit;
            // Tower units stay locked on their platform; only cargo-house units unlock on breach
            if (!_useTowerOverride) then { _garrisonUnits pushBack _unit };
        };
    };

    if (units _grp isEqualTo []) then {
        deleteGroup _grp;
    } else {
        _grp setBehaviourStrong "COMBAT";
        _grp setCombatMode "RED";
        DYN_ground_enemyGroups pushBack _grp;
    };
} forEach _spawnBuildings;

// --- Four static MG posts near the FOB perimeter walls ---
private _mgPosts = [
    [60,  15],
    [65, 195],
    [55, 105],
    [60, 285]
];

{
    private _mgPos = [_fobCenter, _x select 0, _x select 1] call DYN_fnc_posOffset;
    private _mgGrp = createGroup east;

    private _gunner = _mgGrp createUnit ["CUP_O_RU_Soldier_MG_Ratnik_Autumn", _mgPos, [], 0, "NONE"];
    if (!isNull _gunner) then {
        _gunner allowFleeing 0;
        _gunner setSkill 0.85;
        _gunner disableAI "PATH";
        DYN_ground_enemies pushBack _gunner;
    };

    if (units _mgGrp isEqualTo []) then {
        deleteGroup _mgGrp;
    } else {
        _mgGrp setBehaviourStrong "COMBAT";
        _mgGrp setCombatMode "RED";
        DYN_ground_enemyGroups pushBack _mgGrp;
    };
} forEach _mgPosts;

// --- Helipad defence squad (static near the helipad) ---
// The helipad was placed at hardcoded [7430.23,6400.22]; compute its
// relocated position via the same delta that shifted the rest of the FOB.
private _helipadRelPos = [7430.23 + (_delta select 0), 6400.22 + (_delta select 1), 0];
private _helipadGrp = createGroup east;
private _helipadSquadSize = 6 + floor random 3; // 6-8 units

for "_i" from 1 to _helipadSquadSize do {
    private _unitPos = [_helipadRelPos, 3 + random 12, random 360] call DYN_fnc_posOffset;
    if (surfaceIsWater _unitPos) then { _unitPos = _helipadRelPos };

    private _unit = _helipadGrp createUnit [selectRandom _infantryTypes, _unitPos, [], 0, "NONE"];
    if (!isNull _unit) then {
        _unit allowFleeing 0;
        _unit setSkill ["aimingAccuracy", 0.50 + random 0.30];
        _unit setSkill ["aimingShake",    0.40 + random 0.30];
        _unit setSkill ["aimingSpeed",    0.50 + random 0.25];
        _unit setSkill ["spotDistance",   0.75 + random 0.25];
        _unit setSkill ["spotTime",       0.65 + random 0.30];
        _unit setSkill ["courage",        0.85 + random 0.15];
        // Lock in place until breach
        _unit disableAI "MOVE";
        _unit disableAI "PATH";
        _unit disableAI "AUTOCOMBAT";
        DYN_ground_enemies pushBack _unit;
        _garrisonUnits pushBack _unit;
    };
};

if (units _helipadGrp isEqualTo []) then {
    deleteGroup _helipadGrp;
} else {
    _helipadGrp setBehaviourStrong "COMBAT";
    _helipadGrp setCombatMode "RED";
    DYN_ground_enemyGroups pushBack _helipadGrp;
};

// --- Inner compound patrol (2 groups covering the interior) ---
private _innerPatrolGrp = createGroup east;
private _innerPatrolSize = 6 + floor random 3; // 6-8

for "_i" from 1 to _innerPatrolSize do {
    private _unitPos = [_fobCenter, 10 + random 30, random 360] call DYN_fnc_posOffset;
    if (surfaceIsWater _unitPos) then { _unitPos = _fobCenter };

    private _unit = _innerPatrolGrp createUnit [selectRandom _infantryTypes, _unitPos, [], 0, "NONE"];
    if (!isNull _unit) then {
        _unit allowFleeing 0.15;
        _unit setSkill ["aimingAccuracy", 0.45 + random 0.30];
        _unit setSkill ["aimingShake",    0.45 + random 0.30];
        _unit setSkill ["aimingSpeed",    0.50 + random 0.25];
        _unit setSkill ["spotDistance",   0.70 + random 0.25];
        _unit setSkill ["spotTime",       0.65 + random 0.30];
        _unit setSkill ["courage",        0.80 + random 0.20];
        DYN_ground_enemies pushBack _unit;
    };
};

if (units _innerPatrolGrp isEqualTo []) then {
    deleteGroup _innerPatrolGrp;
} else {
    _innerPatrolGrp setBehaviourStrong "AWARE";
    _innerPatrolGrp setCombatMode "RED";
    _innerPatrolGrp setSpeedMode "LIMITED";

    for "_w" from 1 to 4 do {
        private _wPos = [_fobCenter, 10 + random 30, _w * 90] call DYN_fnc_posOffset;
        if (surfaceIsWater _wPos) then { _wPos = _fobCenter };
        private _wp = _innerPatrolGrp addWaypoint [_wPos, 10];
        _wp setWaypointType "MOVE";
        _wp setWaypointBehaviour "AWARE";
        _wp setWaypointCombatMode "RED";
        _wp setWaypointSpeed "LIMITED";
    };
    (_innerPatrolGrp addWaypoint [_fobCenter, 10]) setWaypointType "CYCLE";

    DYN_ground_enemyGroups pushBack _innerPatrolGrp;
};

// Second inner patrol covering opposite arc
private _innerPatrolGrp2 = createGroup east;
private _innerPatrolSize2 = 5 + floor random 3; // 5-7

for "_i" from 1 to _innerPatrolSize2 do {
    private _unitPos = [_fobCenter, 10 + random 25, random 360] call DYN_fnc_posOffset;
    if (surfaceIsWater _unitPos) then { _unitPos = _fobCenter };

    private _unit = _innerPatrolGrp2 createUnit [selectRandom _infantryTypes, _unitPos, [], 0, "NONE"];
    if (!isNull _unit) then {
        _unit allowFleeing 0.15;
        _unit setSkill ["aimingAccuracy", 0.45 + random 0.30];
        _unit setSkill ["aimingShake",    0.45 + random 0.30];
        _unit setSkill ["aimingSpeed",    0.50 + random 0.25];
        _unit setSkill ["spotDistance",   0.70 + random 0.25];
        _unit setSkill ["spotTime",       0.65 + random 0.30];
        _unit setSkill ["courage",        0.80 + random 0.20];
        DYN_ground_enemies pushBack _unit;
    };
};

if (units _innerPatrolGrp2 isEqualTo []) then {
    deleteGroup _innerPatrolGrp2;
} else {
    _innerPatrolGrp2 setBehaviourStrong "AWARE";
    _innerPatrolGrp2 setCombatMode "RED";
    _innerPatrolGrp2 setSpeedMode "LIMITED";

    for "_w" from 1 to 4 do {
        private _wPos = [_fobCenter, 15 + random 25, (_w * 90) + 45] call DYN_fnc_posOffset;
        if (surfaceIsWater _wPos) then { _wPos = _fobCenter };
        private _wp = _innerPatrolGrp2 addWaypoint [_wPos, 10];
        _wp setWaypointType "MOVE";
        _wp setWaypointBehaviour "AWARE";
        _wp setWaypointCombatMode "RED";
        _wp setWaypointSpeed "LIMITED";
    };
    (_innerPatrolGrp2 addWaypoint [_fobCenter, 10]) setWaypointType "CYCLE";

    DYN_ground_enemyGroups pushBack _innerPatrolGrp2;
};

// --- Outer roving patrols — 3 groups circling outside the walls ---
// Uses CYCLE waypoints like hostage-rescue / arms-dealer missions.

// Helper to spawn one outer patrol group
private _fnSpawnOuterPatrol = {
    params ["_center", "_radius", "_size", "_startAngle"];
    private _grp = createGroup east;

    for "_i" from 1 to _size do {
        private _unitPos = [_center, _radius + random 30, random 360] call DYN_fnc_posOffset;
        if (surfaceIsWater _unitPos) then { _unitPos = _center };

        private _unit = _grp createUnit [selectRandom _infantryTypes, _unitPos, [], 0, "NONE"];
        if (!isNull _unit) then {
            _unit allowFleeing 0.2;
            _unit setSkill ["aimingAccuracy", 0.45 + random 0.30];
            _unit setSkill ["aimingShake",    0.45 + random 0.25];
            _unit setSkill ["aimingSpeed",    0.50 + random 0.25];
            _unit setSkill ["spotDistance",   0.70 + random 0.25];
            _unit setSkill ["spotTime",       0.65 + random 0.25];
            _unit setSkill ["courage",        0.75 + random 0.25];
            DYN_ground_enemies pushBack _unit;
        };
    };

    if (units _grp isEqualTo []) then {
        deleteGroup _grp;
    } else {
        _grp setBehaviourStrong "AWARE";
        _grp setCombatMode "RED";
        _grp setSpeedMode "NORMAL";

        // 4-waypoint CYCLE loop around the FOB perimeter
        for "_w" from 1 to 4 do {
            private _wPos = [_center, _radius + random 30, _startAngle + (_w * 90)] call DYN_fnc_posOffset;
            if (surfaceIsWater _wPos) then { _wPos = _center };
            private _wp = _grp addWaypoint [_wPos, 15];
            _wp setWaypointType "MOVE";
            _wp setWaypointBehaviour "AWARE";
            _wp setWaypointCombatMode "RED";
            _wp setWaypointSpeed "NORMAL";
            _wp setWaypointCompletionRadius 15;
        };
        (_grp addWaypoint [_center, _radius]) setWaypointType "CYCLE";

        DYN_ground_enemyGroups pushBack _grp;
    };
};

// Outer patrol 1 — close perimeter (80-110 m)
[_fobCenter, 80, 6 + floor random 3, 0] call _fnSpawnOuterPatrol;      // 6-8

// Outer patrol 2 — medium ring, offset 45 deg (100-130 m)
[_fobCenter, 100, 6 + floor random 3, 45] call _fnSpawnOuterPatrol;     // 6-8

// Outer patrol 3 — wide sweep (130-160 m)
[_fobCenter, 130, 5 + floor random 3, 20] call _fnSpawnOuterPatrol;     // 5-7

diag_log format [
    "[GROUND-FOB] Garrison spawned: %1 groups, %2 infantry total.",
    count DYN_ground_enemyGroups,
    count DYN_ground_enemies
];


// =====================================================
// 5. MARKER AND TASK
// =====================================================
private _taskId = format ["ground_fob_%1", round (diag_tickTime * 1000)];

private _mkr = format ["ground_mkr_fob_%1", round (diag_tickTime * 1000)];
createMarker [_mkr, _zoneCenter];
_mkr setMarkerShape "ELLIPSE";
_mkr setMarkerSize [_zoneRadius, _zoneRadius];
_mkr setMarkerColor "ColorRed";
_mkr setMarkerBrush "FDiagonal";
_mkr setMarkerAlpha 0.4;
_mkr setMarkerText "Enemy FOB";
DYN_ground_markers pushBack _mkr;

[
    west,
    _taskId,
    [
        "Intelligence confirms an active enemy Forward Operating Base. The FOB is heavily garrisoned and houses critical supply assets that sustain enemy operations in the region.<br/><br/>Destroy the following:<br/><br/>- Repair Pod<br/>- Ammunition Pod<br/>- Fuel Pod<br/>- Ammunition Vehicles<br/><br/>Expect a heavily armed garrison. All supply assets must be eliminated.",
        "FOB Hunting",
        ""
    ],
    _zoneCenter,
    "CREATED",
    3,
    true,
    "rifle"
] remoteExec ["BIS_fnc_taskCreate", 0, _taskId];

DYN_ground_tasks pushBack _taskId;

diag_log format ["[GROUND-FOB] Mission active. Zone: %1  FOB: %2", _zoneCenter, _fobCenter];

// =====================================================
// 6. COMPLETION MONITOR
// =====================================================
private _localEnemies  = +DYN_ground_enemies;
private _localGroups   = +DYN_ground_enemyGroups;
private _localObjects  = +DYN_ground_objects;
private _localMarkers  = +DYN_ground_markers;

[
    _taskId, _timeout, _cleanupDelay,
    _repairPod, _ammoPod, _fuelPod, _ammoBoxes,
    _repPerSlingload, _repPerAmmoBox, _repReward,
    _localEnemies, _localGroups, _localObjects, _localMarkers,
    _garrisonUnits, _fobCenter
] spawn {
    params [
        "_tid", "_tOut", "_despawnDelay",
        "_repairPod", "_ammoPod", "_fuelPod", "_ammoBoxes",
        "_repPerSlingload", "_repPerAmmoBox", "_repReward",
        "_localEnemies", "_localGroups", "_localObjects", "_localMarkers",
        "_garrisonUnits", "_fobCenter"
    ];

    private _startTime    = diag_tickTime;
    private _repairDone   = false;
    private _ammoDone     = false;
    private _fuelDone     = false;
    private _ammoBoxDone  = false;
    private _breachFired  = false;  // garrison unlock trigger

    // Helper - vehicle considered destroyed at 90 % damage or when no longer alive
    private _isDead = { (damage _this >= 0.9) || { !alive _this } || { isNull _this } };

    waitUntil {
        sleep 5;

        // ---- Breach trigger: unlock garrison when a player enters the FOB perimeter ----
        if (!_breachFired && count _garrisonUnits > 0) then {
            private _playersNear = { alive _x && _x distance2D _fobCenter < 80 } count allPlayers;
            if (_playersNear > 0) then {
                _breachFired = true;
                diag_log "[GROUND-FOB] Breach detected — garrison units unlocked.";

                // Re-enable AI so garrison can leave buildings and push players
                {
                    if (alive _x) then {
                        _x enableAI "MOVE";
                        _x enableAI "PATH";
                        _x enableAI "AUTOCOMBAT";
                    };
                } forEach _garrisonUnits;

                // Groups are already in COMBAT / RED — they will engage freely now
            };
        };

        // ---- Track destruction (no per-asset rep, awarded all at once on completion) ----
        if (!_repairDone && (_repairPod call _isDead)) then {
            _repairDone = true;
            diag_log "[GROUND-FOB] Repair pod destroyed.";
        };

        if (!_ammoDone && (_ammoPod call _isDead)) then {
            _ammoDone = true;
            diag_log "[GROUND-FOB] Ammo pod destroyed.";
        };

        if (!_fuelDone && (_fuelPod call _isDead)) then {
            _fuelDone = true;
            diag_log "[GROUND-FOB] Fuel pod destroyed.";
        };

        if (!_ammoBoxDone) then {
            private _allGone = (_ammoBoxes findIf { !(_x call _isDead) }) isEqualTo -1;
            if (_allGone && { count _ammoBoxes > 0 }) then {
                _ammoBoxDone = true;
                diag_log "[GROUND-FOB] All ammo vehicles destroyed.";
            };
        };

        // ---- Completion check ----
        private _allDone = _repairDone && _ammoDone && _fuelDone && _ammoBoxDone;
        private _timedOut = (diag_tickTime - _startTime) > _tOut;

        _allDone || _timedOut
    };

    private _allDone = _repairDone && _ammoDone && _fuelDone && _ammoBoxDone;

    if (_allDone) then {
        [_repReward, "FOB Destroyed"] call DYN_fnc_changeReputation;
        [_tid, "SUCCEEDED", false] remoteExec ["BIS_fnc_taskSetState", 0, _tid];
        ["TaskSucceeded", [
            "FOB Hunting complete! All enemy supply assets have been destroyed.",
            "FOB Hunting"
        ]] remoteExecCall ["BIS_fnc_showNotification", 0];
        diag_log format ["[GROUND-FOB] SUCCESS - all targets destroyed. +%1 rep.", _repReward];
    } else {
        [_tid, "FAILED", false] remoteExec ["BIS_fnc_taskSetState", 0, _tid];
        ["TaskFailed", [
            "FOB Hunting Failed",
            "Not all supply assets were destroyed before the deadline."
        ]] remoteExecCall ["BIS_fnc_showNotification", 0];
        diag_log "[GROUND-FOB] TIMED OUT - mission failed.";
    };

    { deleteMarker _x } forEach _localMarkers;
    DYN_ground_markers = DYN_ground_markers - _localMarkers;

    sleep 15;
    [_tid] remoteExec ["BIS_fnc_deleteTask", 0];
    [] remoteExec ["", 0, _tid];

    DYN_ground_active = false;

    diag_log format ["[GROUND-FOB] Despawning in %1 seconds.", _despawnDelay];
    sleep _despawnDelay;

    // Delete infantry and their groups
    { if (!isNull _x) then { deleteVehicle _x } } forEach _localEnemies;
    { if (!isNull _x) then { deleteGroup _x } } forEach _localGroups;

    // Delete all FOB building objects
    { if (!isNull _x) then { deleteVehicle _x } } forEach _localObjects;

    DYN_ground_enemies     = DYN_ground_enemies     - _localEnemies;
    DYN_ground_enemyGroups = DYN_ground_enemyGroups - _localGroups;
    DYN_ground_objects     = DYN_ground_objects     - _localObjects;

    diag_log "[GROUND-FOB] Full cleanup complete.";
};

diag_log "[GROUND-FOB] FOB Hunting mission initialised successfully.";
